apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sd-kafka-sc
  labels:
    app: ibm-spectrum-discover
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "fs1"
    clusterId: "7190932967857929650"  # CNSA storage cluster (remote cluster) ID obtained via mmlscluster
    uid: "1000"
    gid: "1000"
reclaimPolicy: Retain # Important
volumeBindingMode: Immediate # Important

