apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sd-kafka-sc
  labels:
    app: ibm-spectrum-discover
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "scale-jmasc-csplab-cnsa-fs2"
    clusterId: "7190932967857929650"  # CNSA storage cluster (remote cluster) ID obtained from mmlscluster
    uid: "1000"
    gid: "1000"
    permissions: "777" #Important for subPath support, requires IBM Spectrum Scale CSI 2.3.0
reclaimPolicy: Retain # Important
volumeBindingMode: Immediate # Important

